# Generated by Django 5.1.4 on 2025-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
